# ------------------------------------------------------------- #
# Note: this file is automatically managed in template-template #
# ------------------------------------------------------------- #

on: push

jobs:
  metadata:
    runs-on: ubuntu-latest

    outputs:
      repository: ${{ fromJSON(steps.metadata.outputs.repository) }}

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: ahmadnassri/action-metadata@v1
        id: metadata

  test:
    needs: metadata

    runs-on: ubuntu-latest

    steps:
      - run: echo foo
        if: ${{ needs.metadata.outputs.repository.is_template }}

      - run: echo ${{ needs.metadata.outputs.repository.is_template }}
